# config toml for example
[flags]
name = "NZ"
method = "TPWT"
wave = "RAYLEIGH"

[parameters]
threshold = { snr = 10, tmisfit = 8, nsta = 10, valid_ratio = 0.3, dist = 3500 }
inverse = { damping = 0.2, smooth = 90 }
time_delta = 10800
ampcut = 2
tevtrmscut = 8.0
ampevtrmscut = 1.0
dcheck = 2
dvel = 8

[paths]
evt_csv = "data/events.csv"
sta_csv = "data/stations.csv"
sac_dir = "data/SAC"
output_dir = "outputs"
utils = "TPWT/utils"
binpath = "TPWT/bin"

[model]
phvs = [[20, 3.31], [25, 3.32], [30, 3.38], [35, 3.48], [40, 3.51], [45, 3.52],
      [50, 3.53], [60, 3.56], [70, 3.59], [80, 3.62], [90, 3.65], [100, 3.68],
      [111, 3.71], [125, 3.74], [135, 3.76], [143, 3.78]]
region = { west = 172.0, east = 179.0, south = -42, north = -34.0 }
dgrid = 0.5
ref_sta = [177.65, -38.0]
